"""Built by the CAD desk, one accepted cell at a time.

This file is not a record written beside the work; it is the work. Every cell below ran
in the desk's kernel, in this order, and was accepted only after the names it uses were
shown to be bound by a cell above it. It is run from empty at the finish, and what it
makes there is compared against what is in the case directory.

The prose above each cell is the desk's own reasoning for it, carried with the action
rather than thrown away -- it is the only record of why this shape is this shape.
"""

# -- cell 1 -------------------------------------------------------------------------
# I’ll model the gears as straight-tooth bevel solids generated by lofting involute transverse tooth p
import build123d as bd, inspect, math, numpy as np
print('build123d', bd.__version__ if hasattr(bd,'__version__') else 'installed')
print('loft:', inspect.signature(bd.loft))
print('Polygon:', inspect.signature(bd.Polygon))
print('Plane:', inspect.signature(bd.Plane))
print('export_stl:', inspect.signature(bd.export_stl))

# -- cell 2 -------------------------------------------------------------------------
# I’m now building the two coarse lofted gear solids from explicit involute profiles. I’ll sample the 
from build123d import *
# Requested dimensions, metres
m=0.003; z_p=20; z_w=30; alpha=math.radians(20); backlash=0.0003
Lx,Ly,Lz=0.160,0.140,0.120
# Assumptions required by the underspecified enclosure/gear blank
face_width=0.015; shaft_d=0.018
R=0.5*m*math.sqrt(z_p**2+z_w**2)
delta_p=math.atan(z_p/z_w); delta_w=math.atan(z_w/z_p)

def involute_outline(z, phase=0.0, flank_n=5, arc_n=3):
    rp=0.5*m*z; rb=rp*math.cos(alpha); ra=rp+m; rr=rp-1.25*m
    inv=lambda r: math.sqrt((r/rb)**2-1)-math.acos(rb/r)
    invp=inv(rp)
    # split total backlash equally between the two gears
    tooth_thickness=math.pi*m/2-backlash/2
    half=tooth_thickness/(2*rp)
    rs=np.linspace(max(rr,rb),ra,flank_n)
    flank=[half+invp-inv(r) for r in rs]
    pts=[]
    for j in range(z):
        c=phase+2*math.pi*j/z
        # root arc preceding left flank
        aL=flank[0]
        for a in np.linspace(c-math.pi/z+aL,c-aL,arc_n,endpoint=False): pts.append((rr*math.cos(a),rr*math.sin(a)))
        if rr < rb: pts.append((rr*math.cos(c-aL),rr*math.sin(c-aL)))
        for r,aoff in zip(rs,flank): pts.append((r*math.cos(c-aoff),r*math.sin(c-aoff)))
        at=flank[-1]
        for a in np.linspace(c-at,c+at,arc_n,endpoint=False): pts.append((ra*math.cos(a),ra*math.sin(a)))
        for r,aoff in zip(rs[::-1],flank[::-1]): pts.append((r*math.cos(c+aoff),r*math.sin(c+aoff)))
        if rr < rb: pts.append((rr*math.cos(c+aL),rr*math.sin(c+aL)))
    return pts

def bevel_local(z, phase=0):
    d=math.atan(z/(z_w if z==z_p else z_p))
    outer_z=R*math.cos(d); inner_R=R-face_width; inner_z=inner_R*math.cos(d)
    po=involute_outline(z,phase)
    pi=[(x*inner_R/R,y*inner_R/R) for x,y in po]
    wo=Wire.make_polygon([Vector(x,y,outer_z) for x,y in po],close=True)
    wi=Wire.make_polygon([Vector(x,y,inner_z) for x,y in pi],close=True)
    return loft([Face(wi),Face(wo)],ruled=True), inner_z, outer_z
pin_local,pin_zi,pin_zo=bevel_local(z_p,0)
pinion=Rot(0,90,0)*pin_local
wheel0,w_zi,w_zo=bevel_local(z_w,0)
print('R, cone angles, face width:',R,math.degrees(delta_p),math.degrees(delta_w),face_width)
print('volumes:',pinion.volume,wheel0.volume,'valid',pinion.is_valid,wheel0.is_valid)

# -- cell 3 -------------------------------------------------------------------------
phases=np.linspace(0,360/z_w,25)
ivals=[]
for deg in phases:
    w=Rot(0,0,float(deg))*wheel0
    try: ivals.append((deg,(pinion&w).volume))
    except: ivals.append((deg,float('nan')))
print(ivals)
best=min(ivals,key=lambda q:q[1])
wheel_phase_deg=best[0]; wheel=Rot(0,0,wheel_phase_deg)*wheel0
print('chosen wheel phase deg / common solid volume:',wheel_phase_deg,best[1])

# -- cell 4 -------------------------------------------------------------------------
# The coarse phase scan found the expected mesh position at half a wheel pitch (6°); the residual over
# Shafts run away from the cone apex to and slightly through the +X and +Z walls
shaft_r=shaft_d/2
pin_shaft=Rot(0,90,0)*(Pos(0,0,pin_zi)*Cylinder(shaft_r,Lx/2+0.003-pin_zi))
wheel_shaft=Pos(0,0,w_zi)*Cylinder(shaft_r,Lz/2+0.003-w_zi)
pin_assembly=pinion.fuse(pin_shaft)
wheel_assembly=wheel.fuse(wheel_shaft)
solid_union=pin_assembly.fuse(wheel_assembly)
cavity=Pos(-Lx/2,-Ly/2,-Lz/2)*Box(Lx,Ly,Lz,align=(Align.MIN,Align.MIN,Align.MIN))
fluid=cavity-solid_union
print('assembly volumes / overlap / fluid:',pin_assembly.volume,wheel_assembly.volume,(pin_assembly&wheel_assembly).volume,fluid.volume)
print('expected volume check:',cavity.volume-solid_union.volume,'connected solids',len(fluid.solids()),'valid',fluid.is_valid)
print('bbox:',fluid.bounding_box().min,fluid.bounding_box().max,'faces',len(fluid.faces()))

# -- cell 5 -------------------------------------------------------------------------
import os, pyvista as pv
os.makedirs('constant/triSurface',exist_ok=True)
bd.export_stl(solid_union,'coarse_gears_preview.stl',tolerance=0.00035,angular_tolerance=0.18)
meshprev=pv.read('coarse_gears_preview.stl')
pl=pv.Plotter(off_screen=True,window_size=(900,700)); pl.set_background('white')
pl.add_mesh(meshprev,color='goldenrod',show_edges=True,edge_color='#555555')
pl.add_mesh(pv.Box(bounds=(-Lx/2,Lx/2,-Ly/2,Ly/2,-Lz/2,Lz/2)),color='lightblue',opacity=.12,style='wireframe',line_width=2)
pl.add_axes(); pl.view_isometric(); pl.camera.zoom(1.35)
pl.show(screenshot='coarse_geometry.png')
print(meshprev.n_cells, meshprev.bounds)

# -- cell 6 -------------------------------------------------------------------------
# The preview confirms the intended orthogonal bevel arrangement, taper direction, wall exits, and amp
from collections import Counter,defaultdict
cnt=Counter(str(f.geom_type) for f in fluid.faces())
areas=defaultdict(float)
for f in fluid.faces(): areas[str(f.geom_type)]+=f.area
print(cnt)
print(dict(areas))
# summarize cylinders by centers/bounds
cyl=[]
for i,f in enumerate(fluid.faces()):
    if 'CYLINDER' in str(f.geom_type):
        bb=f.bounding_box(); cyl.append((i,f.area,tuple(round(v,5) for v in f.center()),tuple(round(v,5) for v in bb.min),tuple(round(v,5) for v in bb.max)))
print('cyl count',len(cyl)); print(cyl[:20])

# -- cell 7 -------------------------------------------------------------------------
for name,s in [('pin_shaft',pin_shaft),('wheel_shaft',wheel_shaft),('pinion',pinion),('wheel',wheel)]:
 bb=s.bounding_box(); print(name,bb.min,bb.max,s.volume)
print('pin z values',pin_zi,pin_zo,'wheel',w_zi,w_zo)

# -- cell 8 -------------------------------------------------------------------------
# The boundary inspection exposed a placement error before meshing: `Cylinder` defaults to centered ax
pin_len=Lx/2+0.003-pin_zi; wheel_len=Lz/2+0.003-w_zi
pin_shaft=Pos(pin_zi,0,0)*(Rot(0,90,0)*Cylinder(shaft_r,pin_len,align=(Align.CENTER,Align.CENTER,Align.MIN)))
wheel_shaft=Pos(0,0,w_zi)*Cylinder(shaft_r,wheel_len,align=(Align.CENTER,Align.CENTER,Align.MIN))
pin_assembly=pinion.fuse(pin_shaft); wheel_assembly=wheel.fuse(wheel_shaft)
solid_union=pin_assembly.fuse(wheel_assembly); fluid=cavity-solid_union
for name,s in [('pin_shaft',pin_shaft),('wheel_shaft',wheel_shaft),('fluid',fluid)]:
 bb=s.bounding_box(); print(name,bb.min,bb.max)
print('fluid connected/valid/volume/faces',len(fluid.solids()),fluid.is_valid,fluid.volume,len(fluid.faces()))

# -- cell 9 -------------------------------------------------------------------------
groups={'cavityWalls':[],'pinion':[],'wheel':[],'pinionShaftBore':[],'wheelShaftBore':[]}
amb=[]
tol=2e-6
for f in fluid.faces():
    bb=f.bounding_box(); c=f.center(); gt=str(f.geom_type)
    onwall=(abs(bb.min.X+Lx/2)<tol and abs(bb.max.X+Lx/2)<tol) or (abs(bb.min.X-Lx/2)<tol and abs(bb.max.X-Lx/2)<tol) or (abs(bb.min.Y+Ly/2)<tol and abs(bb.max.Y+Ly/2)<tol) or (abs(bb.min.Y-Ly/2)<tol and abs(bb.max.Y-Ly/2)<tol) or (abs(bb.min.Z+Lz/2)<tol and abs(bb.max.Z+Lz/2)<tol) or (abs(bb.min.Z-Lz/2)<tol and abs(bb.max.Z-Lz/2)<tol)
    if onwall: groups['cavityWalls'].append(f)
    elif 'CYLINDER' in gt:
        # Pinion shaft cylinders vary principally in X; wheel shaft cylinders in Z
        if (bb.max.X-bb.min.X) > (bb.max.Z-bb.min.Z): groups['pinionShaftBore'].append(f)
        else: groups['wheelShaftBore'].append(f)
    else:
        pin_ax=(bb.min.X>=pin_zi-1e-5 and bb.max.X<=pin_zo+1e-5)
        wh_ax=(bb.min.Z>=w_zi-1e-5 and bb.max.Z<=w_zo+1e-5)
        if pin_ax and not wh_ax: groups['pinion'].append(f)
        elif wh_ax and not pin_ax: groups['wheel'].append(f)
        elif pin_ax and wh_ax:
            # contact-zone cut faces: assign by which axial span they occupy more tightly
            sx=(bb.max.X-bb.min.X)/(pin_zo-pin_zi); sz=(bb.max.Z-bb.min.Z)/(w_zo-w_zi)
            groups['pinion' if sx>sz else 'wheel'].append(f)
        else: amb.append((gt,tuple(c),bb.min,bb.max,f.area))
print({k:(len(v),sum(f.area for f in v)) for k,v in groups.items()})
print('ambiguous',len(amb)); print(amb[:10])

# -- cell 10 ------------------------------------------------------------------------
# All 862 fluid-boundary faces classify without ambiguity: 6 enclosure faces, 342 pinion faces, 512 wh
tri='constant/triSurface'; os.makedirs(tri,exist_ok=True)
for name,faces in groups.items():
    patch_shape=Compound(faces)
    bd.export_stl(patch_shape,f'{tri}/{name}.stl',tolerance=0.0001,angular_tolerance=0.08,ascii_format=False)
print([(p,os.path.getsize(f'{tri}/{p}.stl')) for p in groups])
# Persist exact CAD too for reproducibility/interchange
bd.export_step(fluid,'oilFluid.step')
print('STEP bytes',os.path.getsize('oilFluid.step'))

# -- cell 11 ------------------------------------------------------------------------
import subprocess
for name in groups:
 r=subprocess.run(['surfaceCheck',f'{tri}/{name}.stl'],text=True,capture_output=True)
 lines=[ln for ln in (r.stdout+r.stderr).splitlines() if any(x in ln for x in ['Triangles','Bounding Box','unconnected','illegal','closed','open edges'])]
 print('\n',name,'rc',r.returncode); print('\n'.join(lines[-8:]))

# -- cell 12 ------------------------------------------------------------------------
bd.export_stl(fluid,'fluidUnionTest.stl',tolerance=0.0001,angular_tolerance=0.08)
r=subprocess.run(['surfaceCheck','fluidUnionTest.stl'],text=True,capture_output=True)
print('\n'.join((r.stdout+r.stderr).splitlines()[-22:]))

# -- cell 13 ------------------------------------------------------------------------
# The complete five-STL union is closed even though each individual patch is necessarily open. I’m sto
os.makedirs('system',exist_ok=True); os.makedirs('constant/polyMesh',exist_ok=True)
open('system/controlDict','w').write('''FoamFile{format ascii;class dictionary;object controlDict;}\napplication snappyHexMesh; startFrom startTime; startTime 0; stopAt endTime; endTime 1; deltaT 1; writeControl timeStep; writeInterval 1;''')
open('system/blockMeshDict','w').write('''FoamFile{format ascii;class dictionary;object blockMeshDict;}\nscale 1;\nvertices ((-0.085 -0.075 -0.065)(0.085 -0.075 -0.065)(0.085 0.075 -0.065)(-0.085 0.075 -0.065)(-0.085 -0.075 0.065)(0.085 -0.075 0.065)(0.085 0.075 0.065)(-0.085 0.075 0.065));\nblocks (hex (0 1 2 3 4 5 6 7) (17 15 13) simpleGrading (1 1 1));\nedges(); boundary(background{type patch;faces((0 4 7 3)(1 2 6 5)(0 1 5 4)(3 7 6 2)(0 3 2 1)(4 5 6 7));}); mergePatchPairs();''')
geom='\n'.join(f'  {n}.stl {{ type triSurfaceMesh; name {n}; }}' for n in groups)
refs='''cavityWalls {level (0 0); patchInfo {type wall;}} pinion {level (2 2); patchInfo {type wall;}} wheel {level (2 2); patchInfo {type wall;}} pinionShaftBore {level (1 1); patchInfo {type wall;}} wheelShaftBore {level (1 1); patchInfo {type wall;}}'''
open('system/snappyHexMeshDict','w').write(f'''FoamFile{{format ascii;class dictionary;object snappyHexMeshDict;}}\ncastellatedMesh true; snap true; addLayers false;\ngeometry{{{geom}}}\ncastellatedMeshControls{{maxLocalCells 300000; maxGlobalCells 400000; minRefinementCells 0; nCellsBetweenLevels 1; resolveFeatureAngle 35; refinementSurfaces{{{refs}}} refinementRegions{{}} locationInMesh (-0.06 0 0); allowFreeStandingZoneFaces true;}}\nsnapControls{{nSmoothPatch 3; tolerance 2.0; nSolveIter 30; nRelaxIter 5; nFeatureSnapIter 0; implicitFeatureSnap false; explicitFeatureSnap false; multiRegionFeatureSnap false;}}\naddLayersControls{{relativeSizes true; layers{{}} expansionRatio 1.0; finalLayerThickness 0.3; minThickness 0.1; nGrow 0; featureAngle 60; nRelaxIter 3; nSmoothSurfaceNormals 1; nSmoothNormals 3; nSmoothThickness 10; maxFaceThicknessRatio 0.5; maxThicknessToMedialRatio 0.3; minMedianAxisAngle 90; nBufferCellsNoExtrude 0; nLayerIter 50;}}\nmeshQualityControls{{#include \"meshQualityDict\"}}\nmergeTolerance 1e-6;''')
print('wrote meshing dictionaries; background cells',17*15*13)

# -- cell 14 ------------------------------------------------------------------------
r=subprocess.run(['blockMesh'],text=True,capture_output=True); print(r.stdout[-2500:]); print(r.stderr[-500:]); print('return',r.returncode)

# -- cell 15 ------------------------------------------------------------------------
# `blockMesh` caught a compact dictionary formatting error before creating any cells. I’m expanding th
open('system/blockMeshDict','w').write('''FoamFile { format ascii; class dictionary; object blockMeshDict; }
scale 1;
vertices
(
(-0.085 -0.075 -0.065) (0.085 -0.075 -0.065) (0.085 0.075 -0.065) (-0.085 0.075 -0.065)
(-0.085 -0.075 0.065) (0.085 -0.075 0.065) (0.085 0.075 0.065) (-0.085 0.075 0.065)
);
blocks ( hex (0 1 2 3 4 5 6 7) (17 15 13) simpleGrading (1 1 1) );
edges ();
boundary
(
 background
 {
  type patch;
  faces
  (
   (0 4 7 3) (1 2 6 5) (0 1 5 4) (3 7 6 2) (0 3 2 1) (4 5 6 7)
  );
 }
);
mergePatchPairs ();
''')
r=subprocess.run(['blockMesh'],text=True,capture_output=True); print('\n'.join(r.stdout.splitlines()[-25:])); print(r.stderr); print('return',r.returncode)

# -- cell 16 ------------------------------------------------------------------------
# The 3,315-cell background mesh now exists. I’m running the coarse surface-cut and snap pass immediat
open('system/meshQualityDict','w').write('''maxNonOrtho 75; maxBoundarySkewness 20; maxInternalSkewness 4; maxConcave 80; minVol 1e-15; minTetQuality 1e-20; minArea -1; minTwist 0.01; minDeterminant 0.001; minFaceWeight 0.02; minVolRatio 0.01; minTriangleTwist -1; nSmoothScale 4; errorReduction 0.75; relaxed {maxNonOrtho 80;}''')
r=subprocess.run(['snappyHexMesh','-overwrite'],text=True,capture_output=True,timeout=240)
open('snappy.log','w').write(r.stdout+r.stderr)
print('\n'.join((r.stdout+r.stderr).splitlines()[-60:])); print('return',r.returncode)

# -- cell 17 ------------------------------------------------------------------------
# The mesher requires standard empty-case numerics dictionaries even though no solver will be run. I’m
open('system/fvSchemes','w').write('''FoamFile{format ascii;class dictionary;object fvSchemes;} ddtSchemes{default steadyState;} gradSchemes{default Gauss linear;} divSchemes{default none;} laplacianSchemes{default Gauss linear corrected;} interpolationSchemes{default linear;} snGradSchemes{default corrected;} wallDist{method meshWave;}''')
open('system/fvSolution','w').write('''FoamFile{format ascii;class dictionary;object fvSolution;} solvers{} SIMPLE{} relaxationFactors{}''')
r=subprocess.run(['snappyHexMesh','-overwrite'],text=True,capture_output=True,timeout=240)
open('snappy.log','w').write(r.stdout+r.stderr)
print('\n'.join((r.stdout+r.stderr).splitlines()[-80:])); print('return',r.returncode)

# -- cell 18 ------------------------------------------------------------------------
# Surface ingestion is successful; OpenFOAM 2512 additionally requires an explicit empty feature list.
p=open('system/snappyHexMeshDict').read(); p=p.replace('refinementRegions{} locationInMesh','refinementRegions{} features(); locationInMesh'); open('system/snappyHexMeshDict','w').write(p)
r=subprocess.run(['snappyHexMesh','-overwrite'],text=True,capture_output=True,timeout=240)
open('snappy.log','w').write(r.stdout+r.stderr)
print('\n'.join((r.stdout+r.stderr).splitlines()[-80:])); print('return',r.returncode)

# -- cell 19 ------------------------------------------------------------------------
print(open('system/snappyHexMeshDict').read())

# -- cell 20 ------------------------------------------------------------------------
# The compact form parsed `features()` incorrectly despite displaying it. I’m rewriting the controls i
p=open('system/snappyHexMeshDict').read(); a=p.index('castellatedMeshControls'); b=p.index('snapControls')
cc='''castellatedMeshControls
{
 maxLocalCells 300000;
 maxGlobalCells 400000;
 minRefinementCells 0;
 nCellsBetweenLevels 1;
 features ();
 refinementSurfaces
 {
  cavityWalls { level (0 0); patchInfo { type wall; } }
  pinion { level (2 2); patchInfo { type wall; } }
  wheel { level (2 2); patchInfo { type wall; } }
  pinionShaftBore { level (1 1); patchInfo { type wall; } }
  wheelShaftBore { level (1 1); patchInfo { type wall; } }
 }
 resolveFeatureAngle 35;
 refinementRegions { }
 locationInMesh (-0.06 0 0);
 allowFreeStandingZoneFaces true;
}
'''
open('system/snappyHexMeshDict','w').write(p[:a]+cc+p[b:])
r=subprocess.run(['snappyHexMesh','-overwrite'],text=True,capture_output=True,timeout=240); open('snappy.log','w').write(r.stdout+r.stderr)
print('\n'.join((r.stdout+r.stderr).splitlines()[-80:])); print('return',r.returncode)

# -- cell 21 ------------------------------------------------------------------------
# The first actual cut-cell mesh completed with 10,640 cells and all five named surface patches. I’m r
r=subprocess.run(['checkMesh','-allGeometry','-allTopology'],text=True,capture_output=True); open('checkMesh.log','w').write(r.stdout+r.stderr); print('\n'.join((r.stdout+r.stderr).splitlines()[-100:])); print('return',r.returncode)

# -- cell 22 ------------------------------------------------------------------------
# The coarse mesh visibly conforms to the cavity and bore opening. I’ll now run the standard binding `
r=subprocess.run(['checkMesh'],text=True,capture_output=True); open('checkMesh.log','w').write(r.stdout+r.stderr); print('\n'.join((r.stdout+r.stderr).splitlines()[-55:])); print('return',r.returncode)

# -- cell 23 ------------------------------------------------------------------------
# The advisory checker found a real export defect: tessellating each B-rep face group independently in
master=pv.read('fluidUnionTest.stl').triangulate(); cc=master.cell_centers().points
P=master.points; F=master.faces.reshape(-1,4)[:,1:]
labels=np.empty(master.n_cells,dtype=object)
for i,(cen,ids) in enumerate(zip(cc,F)):
    verts=P[ids]; x,y,z=cen
    onwall=(np.ptp(verts[:,0])<2e-7 and (abs(x-Lx/2)<2e-7 or abs(x+Lx/2)<2e-7)) or (np.ptp(verts[:,1])<2e-7 and (abs(y-Ly/2)<2e-7 or abs(y+Ly/2)<2e-7)) or (np.ptp(verts[:,2])<2e-7 and (abs(z-Lz/2)<2e-7 or abs(z+Lz/2)<2e-7))
    if onwall: lab='cavityWalls'
    elif x>=pin_zo-2e-5 and x<=Lx/2+2e-5 and abs(math.hypot(y,z)-shaft_r)<4e-4: lab='pinionShaftBore'
    elif z>=w_zo-2e-5 and z<=Lz/2+2e-5 and abs(math.hypot(x,y)-shaft_r)<4e-4: lab='wheelShaftBore'
    else:
        pin_ax=pin_zi-2e-5<=x<=pin_zo+2e-5; wh_ax=w_zi-2e-5<=z<=w_zo+2e-5
        if pin_ax and not wh_ax: lab='pinion'
        elif wh_ax and not pin_ax: lab='wheel'
        elif pin_ax and wh_ax: lab='pinion' if abs((x-(pin_zi+pin_zo)/2)/(pin_zo-pin_zi)) > abs((z-(w_zi+w_zo)/2)/(w_zo-w_zi)) else 'wheel'
        else: raise RuntimeError(('unclassified triangle',i,cen))
    labels[i]=lab
for name in groups:
    ids=np.where(labels==name)[0]; master.extract_cells(ids).extract_surface().triangulate().save(f'{tri}/{name}.stl',binary=True)
print({n:int(np.sum(labels==n)) for n in groups},'total',master.n_cells)

# -- cell 24 ------------------------------------------------------------------------
# The corrected patch files now partition all 108,004 triangles of one manifold master surface exactly
subprocess.run(['blockMesh'],text=True,capture_output=True,check=True)
r1=subprocess.run(['snappyHexMesh','-overwrite'],text=True,capture_output=True,timeout=240); open('snappy.log','w').write(r1.stdout+r1.stderr)
r2=subprocess.run(['checkMesh'],text=True,capture_output=True); open('checkMesh.log','w').write(r2.stdout+r2.stderr)
print('snappy rc',r1.returncode,'check rc',r2.returncode); print('\n'.join((r2.stdout+r2.stderr).splitlines()[-35:]))
